### ISSUE TITLE
comparing estimparam to abcrf

### ISSUE THREAD

**Issue by aestoup** [fradav/abcranger#10]
Made many replicate analyses (from same training set and same statobs) - many estimators compared
Globally seems ok (and substantially quicker): congratulation!
Modulo... mean relative confidence which seems visibly higher in abcrf (> 1.0) than in estimparam (<1.0)
Other relative confidence measure seems (only) a bit different (did not have the time to check that thoroughly).
Note: command line
./EstimParam-20190508-1002-linux -t 1000 --parameter ra --chosenscen 3 --ntrain 1000 --ntest 100

**Comment by fradav** [comment]
Ok, I should double check the confidence part.

**Comment by aestoup** [comment]
Tests on the pygmees dataset, = comparison of abcrf on R and EstimParam on 4 replicate analyses:
- EstimParam quantiles are systematically> to those of abcrf
- variance of estimation (computed from test dataset): EstimParam > abcrf and this for all measures i.e. MSE, NMSE, MMAE, differents CIs measures

**Comment by fradav** [comment]
Ok, nailed it : my variance is the `variance.cdf` which is the one Raynal recommended me to use, which is based on the **expectation** residuals.
![image](https://user-images.githubusercontent.com/701587/58943827-de7fec80-8780-11e9-957a-8e627fafe6cc.png)
The variance you use is based on **oob expectation** residuals : 
![image](https://user-images.githubusercontent.com/701587/58943920-0c653100-8781-11e9-9a6e-c91b6a5bcdb3.png)
I will replace the former by the latter, then.

**Comment by aestoup** [comment]
Good that you pointed that.
Does it also explain that "EstimParam quantiles are systematically> to those of abcrf"? 
Not sure about that.

**Comment by fradav** [comment]
I thought, wrongfully, that once we get the weights, we could apply a standard quantile estimator. Apparently, my quantile estimator is not like the [Meinshauser's one](http://www.jmlr.org/papers/v7/meinshausen06a.html), which is the one abcrf implemented.
Currently converting this to C++ : 
```R
# Quantiles calculation

ord <- order(origObs)
origObs <- origObs[ord]
weights <- weights[ord,,drop=FALSE]
cumweights <- colCumsums(weights)
cumweights <- sweep(cumweights,2,as.numeric(cumweights[nobs,]),FUN="/")

# quantiles (from Meins)

for (qc in 1:length(quantiles)){
  larg <- cumweights<quantiles[qc]
  wc <- colSums(larg)+1
  ind1 <- which(wc<1.1)
  indn1 <- which(wc>1.1)
  quant[ind1,qc] <- rep(origObs[1],length(ind1))
  quantmax <- origObs[wc[indn1]]
  quantmin <- origObs[wc[indn1]-1]
  weightmax <- cumweights[cbind(wc[indn1],indn1)]
  weightmin <- cumweights[cbind(wc[indn1]-1,indn1)]
  factor <- numeric(length(indn1))
  indz <- weightmax-weightmin<10^(-10)
  factor[indz] <- 0.5
  factor[!indz] <- (quantiles[qc]-weightmin[!indz])/(weightmax[!indz]-weightmin[!indz])
  quant[indn1,qc] <- quantmin + factor* (quantmax-quantmin)
}
```

**Comment by fradav** [comment]
done and fixed in #https://github.com/fradav/abcranger/commit/f99486447b14b310167b52cdcd589d3478bf4434
