### ISSUE TITLE
composite parameters

### ISSUE THREAD

**Issue by aestoup** [fradav/abcranger#11]
It is sometimes usefull to make inferences on so called "composite" parameters --> for instance t/N (the ratio between the time of divergence and the effective population size).
We do that with abcrf (see the R code): can we do that with estimParam? If no then we should think about it.

**Comment by fradav** [comment]
The only and fastest way I can think we can implement  this is to ask the user to add the computed composite parameter himself to the data. Otherwise we should implement a symbolic expression interpreter, which is a serious additional development. 

We may also take the computed parameter in a separate file for example.

**Comment by fradav** [comment]
Anyway, I will give a look if I may add a simple symbolic parser for this. Basically what types of composition should we expect ?

**Comment by aestoup** [comment]
Basically any product between TWO parameters or ratio between TWO parameters could be of interest:

For instance:
N * µ (with N an effective population size and µ the mutation rate)
NF / DB (with NF the number of founding individuals and DB the duration of a bottleneck --> corresponds to the so called bottleneck intensity)
t / N (with t a divergence time and N an effective population size --> corresponds to the scaled divergence rate)

One could imagine some interest for products or ratios between more than TWO parameters and/or addition of parameters (eg. t / (N1 + N2 + N3))...but difficult to do in practice and rarely considered.

So as a first coding step = just considering product between TWO parameters or ratio between TWO parameters should do the job.

**Comment by fradav** [comment]
Implemented in https://github.com/fradav/abcranger/commit/eec1b6920119af289e1dfe5b2aac3538682e5acb
Release soon

**Comment by aestoup** [comment]
Nice!
Will you be able to propose a new release that would allow further comparions/test?
Say early next week?
Of course if you need time to solve (i) PLS axes choice and (2) some potential bias in estimation, just take it.
Note: with the new coming release please explain in this forum how to call for an estimation of a composite parameter; for instance though a command line exemple.

**Comment by fradav** [comment]
Early next week (not accounting for the holiday) should be feasible. 
Currently working on the quantile situation.

**Comment by fradav** [comment]
released https://github.com/fradav/abcranger/releases/tag/1.03
