### ISSUE TITLE
PLS computation seems to fail at least for some tested cases

### ISSUE THREAD

**Issue by aestoup** [fradav/abcranger#12]
I have analyzed a complex case = reference table with  > 10000 summary stats, > 10 particules.
Computation ended in 1 hour on my private cluster (32 cores) and results make sense; but "0 PLS axes" retained is mentioned in the output, which suggests some pbl when computing PLS.

This might be:
- due to the very large number of PLS axes to compute (> 100000)
or
- something similar to the pbl you previously had (and corrected nicely) when computing LDA axes for model choice
or
- something else.

I will thirsday (tomorrow):
- put on the filesender of renater the problematic case for you (cf. big directory)
- try the pygmee data case that you have previously copied on your computer to deal with the LDA axes pbl (so that you can do your own testing if you prefer).

**Comment by fradav** [comment]
Quick look at the code: just realized I put the same crappy solver (which just crashes in the case of no-full-rank data) in PLS that I did in LDA before… Should be easily fixed.

**Comment by fradav** [comment]
Spoke too soon, there is no inverse in the pls computation, so the basic eigen solver should be ok.

I tried the pygmee data (which was crashing LDA previsously) with : 
EstimParam --parameter ra4 --ntrain 1000 --ntest 50 --chosenscen 6
The PLS composants are ok, first lines of the importance file : 
```plain
Comp 1: 17.9355
AMO_1_1&4&5: 7.25457
AP0_1_4&1&5: 5.95983
AP0_1_5&1&4: 5.08979
FP0_1_1&4: 1.75582
RP0_1_5&1&4: 1.41967
AM1_1_1&4&5: 1.32806
RP0_1_4&1&5: 1.00527
FP0_1_1&5: 0.721216
RP0_1_4&1&2: 0.654202
ZMO_1_1&3&4&5: 0.638781
RP0_1_5&1&2: 0.566946
RMO_1_4&1&2: 0.47373
RMO_1_5&1&2: 0.441649
AMO_1_5&1&3: 0.437797
AMO_1_4&1&3: 0.36725
RMO_1_5&1&3: 0.334672
RMO_1_4&1&3: 0.314066
AP0_1_5&1&3: 0.250309
AMO_1_1&2&5: 0.209318
AM1_1_1&2&4: 0.19163
FMO_1_1&5: 0.180203
AM1_1_1&2&5: 0.175933
RMO_1_4&1&5: 0.173187
AMO_1_3&4&5: 0.163892
FMO_1_1&4: 0.162532
Comp 2: 0.161041
RP0_1_4&2&5: 0.158753
RMO_1_5&1&4: 0.156219
AP0_1_5&1&2: 0.156176
AP0_1_4&1&3: 0.144492
AMO_1_1&3&4: 0.0969237
Comp 9: 0.096779
````

**Comment by fradav** [comment]
I got it, the "search 99% explained variance component" routine was wrong (hence selecting 0 pls components in some cases). Anyway I put the new heuristic in motion and a new release, I'll keep this issue open to get your report on the new routine.
